### PR TITLE
How about Code Style?

### PR DESCRIPTION
**Pull request by robinlehrmann**
Hi,

I would prefer you use php cs fixer, to prevent wrong code style.
The checks are already done in this Pull Request.

### CODE REVIEW

**Comment by Techworker** [comment]
Hi Robin,

thanks for that. I had sth. along the lines but didn't use it consistently. https://github.com/Techworker/iota-php/blob/master/.docker/Makefile#L19-L23

**Comment by robinlehrmann** [comment]
Oh, I don't see that 👍  maybe we can move it to the root directory and add my config to it ?

**Comment by Techworker** [comment]
I think your proposal is much better, I'm not sure about the `.docker` folder at all. So yes, we should move the `makefile` to the root then and maybe remove the `.docker` folder and the docker related commands from the makefile as I can't / won't / don't want to support ppl. having problems with it.

The kitchen_sink generation could also be added as a command in the makefile (`var/generate_kitchensink.php`), but that can be done later on.

**Comment by robinlehrmann** [comment]
Okay, that sounds good. Could you merge it ? :)
What do you mean with ppl ? I think docker is a good software, but we should use vagrant with ansible do you know it ? With them, we can create a debian devbox with the required php-extensions and correct versions, if someone don't want to install the php tools on the host system.

**Comment by Techworker** [comment]
I'll merge it, of course! We can talk about the rules you added later.

With docker: I think that's out of scope for this library, if someone has problems with the Dockerfile or whatever I'm not sure if I could support them - it's just cobbled together, I don't have any deep docker (or devops) knowledge. But I'll create an issue for it where we can discuss this further.

Thanks Robin!

**Comment by robinlehrmann** [comment]
Thanks for merging :) I have already created some issues. You can read it out and we can discuss about some things.

**Pull request merged**
