### PR TITLE
Moved namespace

### PR DESCRIPTION
**Pull request by robinlehrmann**
This pull-request requires an update at packagist.
We should abandon the old repository and move it to the new packagist name "iota-php/iota-php".
https://packagist.org/packages/techworker/iota-php 

The update web-hook should be part of this repository, but that is sure.

I was thinking about another name. Is "iota-php/client" a good alternative name?

Additionally I would suggest to remove the src directory. We can move the Code in the root folder. 

But first I will move the examples to another repository.

We can think and talk about the suggestion, to move the code in the root dir in discord.

Cheers,
Robin

### CODE REVIEW

**Comment by Techworker** [comment]
I like the `IOTA\Client` namespace suggestion - packagist would be `iota-php/client`

**Comment by robinlehrmann** [comment]
@Techworker Okay, I will move the composer name to it.

**Comment by robinlehrmann** [comment]
@Techworker is this PR okay for you :) ?

**Comment by Techworker** [comment]
See my comment in #41

**Comment by Techworker** [comment]
Please fix the conflicts, thx

**Review by Techworker — APPROVED** [review]

**Pull request merged**
