### PR TITLE
removed container in IOTA class

### PR DESCRIPTION
**Pull request by robinlehrmann**
belongs to #29

### CODE REVIEW

**Review by DavidBadura — APPROVED** [review]
looks good 👍

**Comment by Techworker** [comment]
Please resolve the conflicts - and please, just for now until you are more into the lib: don't change the visibility of properties yet.

**Comment by robinlehrmann** [comment]
@Techworker I think if we change the visibility of this attributes it doesn't matter in this case. A client user wont never change the attribute in a parent class. It is a thin wrapper of Remote and Client API and if you take a look at SOLID:
```
S | Single responsibility principle class should have only a single responsibility (i.e. changes to only one part of the software's specification should be able to affect the specification of the class).
O | Open/closed principle“software entities … should be open for extension, but closed for modification.”
L | Liskov substitution principle“objects in a program should be replaceable with instances of their subtypes without altering the correctness of that program.” See also design by contract.
I | Interface segregation principle“many client-specific interfaces are better than one general-purpose interface.”
D | Dependency inversion principle one should “depend upon abstractions, [not] concretions.”
```

The open/closed principle says that you don't want to change the internal attributes.

Merge conflicts are resolved.

**Review by Techworker — APPROVED** [review]
Approved

**Pull request merged**
